name: CI to Server

on:
  push:
    branches:
      - "main"

env:
  NAME: yolov8

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: registry.cn-hangzhou.aliyuncs.com/dongxin/${{ env.NAME }}:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: root
          password: ${{ secrets.PASSWORD }}
          script: |
            sudo docker compose -f /opt/compose/${{ env.NAME }}/docker-compose.yml pull ${{ env.NAME }}
            sudo docker compose -f /opt/compose/${{ env.NAME }}/docker-compose.yml up -d --force-recreate --build ${{ env.NAME }}
